services:
  pharmacy_service:
    build: ./backend/services/pharmacy
    image: "pharmacy-service"
    container_name: "pharmacy-service"
    ports:
      - "8000:8000"
    networks:
      - pharmacychain

  medication_service:
    build: ./backend/services/medication
    image: "medication-service"
    container_name: "medication-service"
    ports:
      - "8001:8000"
    networks:
      - pharmacychain

  nginx_gateway:
    image: nginx:latest
    container_name: "api-gateway"
    ports:
      - "80:80"
    volumes:
      - ./backend/services/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./backend/services/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - pharmacychain
    depends_on:
      - pharmacy_service
      - medication_service

networks:
  pharmacychain: